SITE_SERVER_HOST = '51.140.39.156'
SITE_SERVER_PORT = 5010

EXTERNAL_SERVER_HOST = '51.140.39.174'
EXTERNAL_SERVER_PORT = 5001

EXTERNAL_SERVER_HOST_STATS_ANALYSIS = '127.0.0.1'
EXTERNAL_SERVER_PORT_STATS_ANALYSIS = 5003

SITE_SERVER_URL = "http://%s:%s" % (SITE_SERVER_HOST, SITE_SERVER_PORT)
EXTERNAL_SERVER_URL = "http://%s:%s/hints" % (EXTERNAL_SERVER_HOST, EXTERNAL_SERVER_PORT)
EXTERNAL_SERVER_URL_STATS_ANALYSIS = "http://%s:%s" % (EXTERNAL_SERVER_HOST_STATS_ANALYSIS, EXTERNAL_SERVER_PORT_STATS_ANALYSIS)


SAMPLE_DATA_MAX = 5000

